version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "main_db"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "qwerty12345"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

volumes:
  habrdb-data: